Idiomatic elixir, use credo
cpjk/canary pull request #54
Opened 2017-02-11 18:26 UTC by davydog187

I've been using canary in a side project of mine, and noticed that the codebase could be cleaned up a bit in terms of idiomatic elixir code.

Made several changes to simplify code, and make it more idiomatic.

As far as credo goes, disabled PipeChainStart and Specs

2017-02-16 01:37 UTC, cpjk commented on lib/canary/plugs.ex
> +    get_map_args = %{String.to_atom(field_name) => get_resource_id(conn, opts)}
Thanks for cleaning this up!

2017-02-16 01:55 UTC, cpjk requested changes
Overall, great changes. 

Thanks for cleaning things up! :smile: 

Just one small nitpick: if we're going to use yoda assignment in function arguments, it should be consistent throughout the file, e.g. https://github.com/cpjk/canary/pull/54/files#diff-3938ea297feb0d441ffe05cec9da28eaR279

Other than that, LGTM.

2017-02-16 01:55 UTC, cpjk commented on lib/canary/plugs.ex
> +    get_map_args = %{String.to_atom(field_name) => get_resource_id(conn, opts)}
Thanks for cleaning this up!

2017-02-16 01:55 UTC, cpjk commented on lib/canary/plugs.ex
> +  defp handle_unauthorized(%{skip_canary_handler: true} = conn, _opts),
I like the yoda syntax, but if we are going to use it here, it should be used throught the whole code base for consistency, e.g. https://github.com/cpjk/canary/pull/54/files#diff-3938ea297feb0d441ffe05cec9da28eaR282

2017-03-03 22:53 UTC, davydog187 commented
@cpjk Addressed the other yoda cases. Also fixed the merge conflict. Should be good now

2017-03-08 02:53 UTC, cpjk commented
Sorry for the delay! The email got caught up in my work github notifications :smile:.

LGTM! :rocket:

2017-03-08 02:53 UTC, merged